#! /bin/sh

#check there is a vali first argument
if [ "$1" = "" ]
then
    echo "No source file specified. Please specify your source file."
    exit -1
fi

#check there is a valid second argument
if [ "$2" = "" ]
then
    echo "No destination supplied please specify a destination file name."
    exit -1
fi

#Echo description of conversion
echo "Converting "$1" to "$2".mp4"

#Echo step 1 - extraction
echo "Extracting audio and video from matroska file."

#rip the audio and video from the mkv
mkvextract tracks "$1" -q 1:video.264 2:audio.ac3

#Echo step 2 - conversion
echo "Converting audio stream from ac3 to aac, this can take a few minutes."

#convert the audio to aac
ffmpeg -loglevel error -i audio.ac3 audio.aac

#Echo step 3 - merge
echo "Merging the resulting audio and video."

#merge the files
sublerCLI -dest "$2".mp4 -source video.264 > /dev/null
sublerCLI -dest "$2".mp4 -source audio.aac > /dev/null

#Echo cleanup
echo "Cleaning up."

#cleanup
rm audio.ac3
rm audio.aac
rm video.264

#Echo done
echo "Done."
