#! /bin/sh

SOURCE=
DESTINATION=

function extract {

    #Echo step 1 - extraction
    echo "Extracting audio and video from matroska file."

    #rip the audio and video from the mkv
    mkvextract tracks $SOURCE -q 1:video.264 2:audio.ac3

}

function convertAudio {

    #Echo step 2 - conversion
    echo "Converting audio stream from ac3 to aac, this can take a few minutes."

    #convert the audio to aac
    ffmpeg -loglevel error -i audio.ac3 audio.aac

}

function merge {

    #Echo step 3 - merge
    echo "Merging the resulting audio and video."

    #merge the files
    sublerCLI -dest $DESTINATION.mp4 -source video.264 > /dev/null
    sublerCLI -dest $DESTINATION.mp4 -source audio.aac > /dev/null

}

function cleanup {

    #Echo cleanup
    echo "Cleaning up."

    #cleanup
    rm audio.ac3
    rm audio.aac
    rm video.264

}

function usage {

    #print the usage of the script to the console
    echo "usage: muxkv [[[-s source-file] [-d destination-file-name]] | [-h help]]"

}

#####MAIN

#Checks to make sure arguments have been supplied
if [ "$1" = "" ]
then 
    usage
    exit 1
fi

#read the rest of the arguments
while [ "$1" != "" ]; do

    case $1 in

        -s | --source )         shift
                                SOURCE="$1"
                                echo $SOURCE
                                ;;
        -d | --destination )    shift
                                DESTINATION=$1
                                echo $DESTINATION
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac

    shift

done 
                            

#Echo description of conversion
echo "Converting $SOURCE to $DESTINATION.mp4"

#extract streams
extract

#convert the audio
convertAudio

#merge the new audio and video to the .mp4
merge

#cleanup temp files
cleanup 

#Echo done
echo "Done."



